import React from 'react';
const Home = () => {
  return (
    <>
      <main id="home-page">
        <br />
        <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
        this is home page <br />
      </main>
    </>
  );
};

export default Home;
